SET TIME ON
SET TIMING ON
SPOOL DROP_SCHEMA.LOG

DEFINE USER_NAME = &&1
DEFINE TABLESPACE_NAME = &&2

SET SERVEROUTPUT ON

PROMPT *********
PROMPT Username caling to drop_user: &&USER_NAME
@drop_user.sql &&USER_NAME
PROMPT *********
PROMPT

PROMPT *********
PROMPT Username caling to drop_tablspace: &&TABLESPACE_NAME
@drop_tablespace.sql &&TABLESPACE_NAME
PROMPT *********
PROMPT

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE TABLESPACE_NAME

SPOOL OFF