CREATE TABLE PLAYER_STATISTICS (
	STATISTIC_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	PLAYER_ID NUMBER NOT NULL,
	SEASON_ID NUMBER NOT NULL,
	GOALS_NUMBER NUMBER,
	CONSTRAINTS PLAYER_STATISTICS_PK PRIMARY KEY (STATISTIC_ID)
);
