CREATE TABLE COACHES (
	COACH_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	TEAM_ID NUMBER NOT NULL,
	SEASON_ID NUMBER NOT NULL,
	NAME VARCHAR2(100),
	RANK VARCHAR2(100),
	CONSTRAINTS COACH_ID_PK PRIMARY KEY (COACH_ID)
);