CREATE TABLE STADIUMS (
	STADIUM_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	TEAM_ID NUMBER,
	NAME VARCHAR2(100),
	CITY VARCHAR2(100),
	CAPACITY NUMBER,
	CONSTRAINTS STADIUM_ID_PK PRIMARY KEY (STADIUM_ID)
);