DEFINE USER_NAME = &&1
DEFINE INDEX_TBS_NAME = '&&USER_NAME._IDX'

ALTER TABLE TEAM_STATISTICS ADD CONSTRAINT TEAM_ID_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAMS(TEAM_ID);
ALTER TABLE TEAM_STATISTICS ADD CONSTRAINT SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID);
ALTER TABLE PLAYER_STATISTICS ADD CONSTRAINT PLAYER_STATISTICS_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID);
ALTER TABLE PLAYER_STATISTICS ADD CONSTRAINT PLAYER_ID_FK FOREIGN KEY(PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID);
ALTER TABLE STADIUMS ADD CONSTRAINT STADIUMS_TEAM_ID_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAMS(TEAM_ID);
ALTER TABLE TEAMS ADD CONSTRAINT TEAMS_LEAGUE_ID_FK FOREIGN KEY(LEAGUE_ID) REFERENCES LEAGUES(LEAGUE_ID);
ALTER TABLE MATCHES ADD CONSTRAINT MATCHES_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID);
ALTER TABLE COACHES ADD CONSTRAINT COACHES_TEAM_ID_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAMS(TEAM_ID);
ALTER TABLE COACHES ADD CONSTRAINT COACHES_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID);
ALTER TABLE EVENTS ADD CONSTRAINT EVENTS_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID);
ALTER TABLE EVENTS ADD CONSTRAINT EVENTS_MATCH_ID_FK FOREIGN KEY(MATCH_ID) REFERENCES MATCHES(MATCH_ID);

UNDEFINE USER_NAME
UNDEFINE INDEX_TBS_NAME