DEFINE USER_NAME = &&1
DEFINE INDEX_TBS_NAME = '&&USER_NAME._INDEX'

ALTER TABLE TEAM_STATISTICS ADD CONSTRAINT TEAM_ID_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAMS(TEAM_ID);
CREATE INDEX PLAYER_STATISTICS_SEASON_ID_FK_IDX ON PLAYER_STATISTICS(SEASON_ID) TABLESPACE &&INDEX_TBS_NAME	

ALTER TABLE TEAM_STATISTICS ADD CONSTRAINT SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID);
CREATE INDEX PLAYER_ID_FK_IDX ON PLAYER_STATISTICS (PLAYER_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE PLAYER_STATISTICS ADD CONSTRAINT PLAYER_STATISTICS_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID);
CREATE INDEX TEAM_ID_FK_IDX ON TEAM_STATISTICS (TEAM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE PLAYER_STATISTICS ADD CONSTRAINT PLAYER_ID_FK FOREIGN KEY(PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID);
CREATE INDEX SEASON_ID_FK_IDX ON TEAM_STATISTICS (SEASON_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE TEAMS ADD CONSTRAINT TEAMS_LEAGUE_ID_FK FOREIGN KEY(LEAGUE_ID) REFERENCES LEAGUES(LEAGUE_ID);
CREATE INDEX TEAMS_LEAGUE_ID_FK_IDX ON TEAMS (LEAGUE_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE MATCHES ADD CONSTRAINT MATCHES_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID);
CREATE INDEX MATCHES_SEASON_ID_FK_IDX ON MATCHES(SEASON_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE MATCHES ADD CONSTRAINT MATCHES_STADIUM_ID_FK FOREIGN KEY(STADIUM_ID) REFERENCES STADIUMS(STADIUM_ID);
CREATE INDEX MATCHES_STADIUM_ID_FK_IDX ON MATCHES(STADIUM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE COACHES ADD CONSTRAINT COACHES_TEAM_ID_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAMS(TEAM_ID);
CREATE INDEX COACHES_TEAM_ID_FK_IDX ON COACHES (TEAM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE COACHES ADD CONSTRAINT COACHES_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID);
CREATE INDEX COACHES_SEASON_ID_FK_IDX ON COACHES (SEASON_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE EVENTS ADD CONSTRAINT EVENTS_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID);
CREATE INDEX EVENTS_SEASON_ID_FK_IDX ON EVENTS (SEASON_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE EVENTS ADD CONSTRAINT EVENTS_MATCH_ID_FK FOREIGN KEY(MATCH_ID) REFERENCES MATCHES(MATCH_ID);
CREATE INDEX EVENTS_MATCH_ID_FK_IDX ON EVENTS(MATCH_ID) TABLESPACE &&INDEX_TBS_NAME

UNDEFINE USER_NAME
UNDEFINE INDEX_TBS_NAME