DEFINE USER_NAME = &&1
DEFINE TBS_LOCATION = &&2
DEFINE TBS_TYPE = &&3
DEFINE TYPE_TBS_NAME = '&&USER_NAME._&&TBS_TYPE'
DEFINE TYPE_FILENAME =  '&&TBS_LOCATION&&TYPE_TBS_NAME..dbf'

PROMPT &&TYPE_TBS_NAME
PROMPT &&TYPE_FILENAME

CREATE TABLESPACE  &&TYPE_TBS_NAME
    DATAFILE 
        '&&TYPE_FILENAME' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 10G;
        
UNDEFINE USER_NAME;
UNDEFINE TBS_LOCATION;
UNDEFINE TBS_TYPE
UNDEFINE TYPE_TBS_NAME;
UNDEFINE TYPE_FILENAME;