DEFINE SCHEMA_NAME = &&1

GRANT CREATE SEQUENCE TO &&SCHEMA_NAME;
GRANT CREATE TABLE TO &&SCHEMA_NAME;
GRANT CREATE TYPE TO &&SCHEMA_NAME;
GRANT CREATE SYNONYM TO &&SCHEMA_NAME;
GRANT CREATE SESSION TO &&SCHEMA_NAME;
GRANT CREATE PROCEDURE TO &&SCHEMA_NAME;
GRANT CREATE TRIGGER TO &&SCHEMA_NAME;
GRANT CREATE VIEW TO &&SCHEMA_NAME;
GRANT CREATE ANY DIRECTORY TO &&SCHEMA_NAME;
ALTER USER &&SCHEMA_NAME QUOTA UNLIMITED ON &&SCHEMA_NAME._DATA;
ALTER USER &&SCHEMA_NAME QUOTA UNLIMITED ON &&SCHEMA_NAME._INDEX;

UNDEFINE SCHEMA_NAME
