SET SERVEROUTPUT ON;
DECLARE CountRows NUMBER;
BEGIN

SELECT COUNT(*) INTO CountRows FROM COACHES;
DBMS_OUTPUT.PUT_LINE('COACHES - CountRows: ' || CountRows);
SELECT COUNT(*) INTO CountRows FROM LEAGUES;
DBMS_OUTPUT.PUT_LINE('LEAGUES - CountRows: ' || CountRows);
SELECT COUNT(*) INTO CountRows FROM MATCHES;
DBMS_OUTPUT.PUT_LINE('MATCHES: ' || CountRows);
SELECT COUNT(*) INTO CountRows FROM PLAYER_STATISTICS;
DBMS_OUTPUT.PUT_LINE('PLAYER_STATISTICS: ' || CountRows);
SELECT COUNT(*) INTO CountRows FROM PLAYERS;
DBMS_OUTPUT.PUT_LINE('PLAYERS: ' || CountRows);
SELECT COUNT(*) INTO CountRows FROM SEASONS;
DBMS_OUTPUT.PUT_LINE('SEASONS: ' || CountRows);
SELECT COUNT(*) INTO CountRows FROM STADIUMS;
DBMS_OUTPUT.PUT_LINE('STADIUMS: ' || CountRows);
SELECT COUNT(*) INTO CountRows FROM TEAM_STATISTICS;
DBMS_OUTPUT.PUT_LINE('TEAM_STATISTICS: ' || CountRows);
SELECT COUNT(*) INTO CountRows FROM TEAMS;
DBMS_OUTPUT.PUT_LINE('TEAMS: ' || CountRows);
SELECT COUNT(*) INTO CountRows FROM EVENTS;
DBMS_OUTPUT.PUT_LINE('EVENTS: ' || CountRows);

END;