DELETE FROM COACHES;
DELETE FROM LEAGUES;
DELETE FROM MATCHES;
DELETE FROM PLAYER_STATISTICS;
DELETE FROM PLAYERS;
DELETE FROM SEASONS;
DELETE FROM STADIUMS;
DELETE FROM TEAM_STATISTICS;
DELETE FROM TEAMS;
DELETE FROM EVENTS;

commit;